---
- hosts: all
  become: True
  tasks:
   - name: Install packages
     yum:
       name: "httpd"
       state: "present"

   - name: start apache server
     service:
       name: httpd
       state: started
       enabled: True
       
   - name: Deploy
     copy:
       src: index.html
       dest: /var/ww/html  
